load("@io_bazel_rules_go//go:def.bzl", "go_library")

package(default_visibility=["//visibility:public"])

go_library(
    name = "id",
    srcs = ["id.go"],
    importpath = "github.com/downflux/game/engine/id/id",
)

