// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: engine/fsm/api/constants.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace DF.Game.Engine.FSM.API.Constants {

  /// <summary>Holder for reflection information generated from engine/fsm/api/constants.proto</summary>
  public static partial class ConstantsReflection {

    #region Descriptor
    /// <summary>File descriptor for engine/fsm/api/constants.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static ConstantsReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Ch5lbmdpbmUvZnNtL2FwaS9jb25zdGFudHMucHJvdG8SHWdhbWUuZW5naW5l",
            "LmZzbS5hcGkuY29uc3RhbnRzKqYBCgdGU01UeXBlEhQKEEZTTV9UWVBFX1VO",
            "S05PV04QABIRCg1GU01fVFlQRV9NT1ZFEAESFAoQRlNNX1RZUEVfUFJPRFVD",
            "RRACEhIKDkZTTV9UWVBFX0NIQVNFEAMSEwoPRlNNX1RZUEVfQVRUQUNLEAQS",
            "HQoZRlNNX1RZUEVfUFJPSkVDVElMRV9TSE9PVBAFEhQKD0ZTTV9UWVBFX0NM",
            "SUVOVBDoBypdCgpDaGFzZVN0YXRlEhcKE0NIQVNFX1NUQVRFX1VOS05PV04Q",
            "ABIYChRDSEFTRV9TVEFURV9JTl9SQU5HRRABEhwKGENIQVNFX1NUQVRFX09V",
            "VF9PRl9SQU5HRRACKkAKC0F0dGFja1N0YXRlEhgKFEFUVEFDS19TVEFURV9V",
            "TktOT1dOEAASFwoTQVRUQUNLX1NUQVRFX0ZJUklORxABKpMBCgtDb21tb25T",
            "dGF0ZRIYChRDT01NT05fU1RBVEVfVU5LTk9XThAAEhgKFENPTU1PTl9TVEFU",
            "RV9QRU5ESU5HEAESGgoWQ09NTU9OX1NUQVRFX0VYRUNVVElORxACEhkKFUNP",
            "TU1PTl9TVEFURV9DQU5DRUxFRBADEhkKFUNPTU1PTl9TVEFURV9GSU5JU0hF",
            "RBAEQkJaHWdhbWUuZW5naW5lLmZzbS5hcGkuY29uc3RhbnRzqgIgREYuR2Ft",
            "ZS5FbmdpbmUuRlNNLkFQSS5Db25zdGFudHNiBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::DF.Game.Engine.FSM.API.Constants.FSMType), typeof(global::DF.Game.Engine.FSM.API.Constants.ChaseState), typeof(global::DF.Game.Engine.FSM.API.Constants.AttackState), typeof(global::DF.Game.Engine.FSM.API.Constants.CommonState), }, null, null));
    }
    #endregion

  }
  #region Enums
  public enum FSMType {
    [pbr::OriginalName("FSM_TYPE_UNKNOWN")] Unknown = 0,
    [pbr::OriginalName("FSM_TYPE_MOVE")] Move = 1,
    [pbr::OriginalName("FSM_TYPE_PRODUCE")] Produce = 2,
    [pbr::OriginalName("FSM_TYPE_CHASE")] Chase = 3,
    [pbr::OriginalName("FSM_TYPE_ATTACK")] Attack = 4,
    [pbr::OriginalName("FSM_TYPE_PROJECTILE_SHOOT")] ProjectileShoot = 5,
    [pbr::OriginalName("FSM_TYPE_CLIENT")] Client = 1000,
  }

  /// <summary>
  /// TODO(minkezhang): Migrate to //server/fsm/api/.
  /// </summary>
  public enum ChaseState {
    [pbr::OriginalName("CHASE_STATE_UNKNOWN")] Unknown = 0,
    [pbr::OriginalName("CHASE_STATE_IN_RANGE")] InRange = 1,
    [pbr::OriginalName("CHASE_STATE_OUT_OF_RANGE")] OutOfRange = 2,
  }

  /// <summary>
  /// TODO(minkezhang): Migrate to //server/fsm/api/.
  /// </summary>
  public enum AttackState {
    [pbr::OriginalName("ATTACK_STATE_UNKNOWN")] Unknown = 0,
    [pbr::OriginalName("ATTACK_STATE_FIRING")] Firing = 1,
  }

  public enum CommonState {
    [pbr::OriginalName("COMMON_STATE_UNKNOWN")] Unknown = 0,
    [pbr::OriginalName("COMMON_STATE_PENDING")] Pending = 1,
    [pbr::OriginalName("COMMON_STATE_EXECUTING")] Executing = 2,
    /// <summary>
    /// External cancellation due to explicit call or implicitly via precedence
    /// testing.
    /// </summary>
    [pbr::OriginalName("COMMON_STATE_CANCELED")] Canceled = 3,
    [pbr::OriginalName("COMMON_STATE_FINISHED")] Finished = 4,
  }

  #endregion

}

#endregion Designer generated code
