load("@io_bazel_rules_go//go:def.bzl", "go_library", "go_test")

go_library(
    name = "id",
    srcs = ["id.go"],
    importpath = "github.com/downflux/game/server/id",
    visibility = [
        "//visibility:public",
    ],
)

