// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: engine/server/client/api/constants.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace DF.Game.Engine.Server.Client.API.Constants {

  /// <summary>Holder for reflection information generated from engine/server/client/api/constants.proto</summary>
  public static partial class ConstantsReflection {

    #region Descriptor
    /// <summary>File descriptor for engine/server/client/api/constants.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static ConstantsReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CihlbmdpbmUvc2VydmVyL2NsaWVudC9hcGkvY29uc3RhbnRzLnByb3RvEidn",
            "YW1lLmVuZ2luZS5zZXJ2ZXIuY2xpZW50LmFwaS5jb25zdGFudHMqiAEKC0Ns",
            "aWVudFN0YXRlEhgKFENMSUVOVF9TVEFURV9VTktOT1dOEAASFAoQQ0xJRU5U",
            "X1NUQVRFX05FVxABEhkKFUNMSUVOVF9TVEFURV9ERVNZTkNFRBACEhMKD0NM",
            "SUVOVF9TVEFURV9PSxADEhkKFUNMSUVOVF9TVEFURV9URUFSRE9XThAEQlZa",
            "J2dhbWUuZW5naW5lLnNlcnZlci5jbGllbnQuYXBpLmNvbnN0YW50c6oCKkRG",
            "LkdhbWUuRW5naW5lLlNlcnZlci5DbGllbnQuQVBJLkNvbnN0YW50c2IGcHJv",
            "dG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::DF.Game.Engine.Server.Client.API.Constants.ClientState), }, null, null));
    }
    #endregion

  }
  #region Enums
  /// <summary>
  /// ClientState represents the internal game's awareness of the current
  /// networking state of a connected client.
  /// </summary>
  public enum ClientState {
    [pbr::OriginalName("CLIENT_STATE_UNKNOWN")] Unknown = 0,
    [pbr::OriginalName("CLIENT_STATE_NEW")] New = 1,
    [pbr::OriginalName("CLIENT_STATE_DESYNCED")] Desynced = 2,
    [pbr::OriginalName("CLIENT_STATE_OK")] Ok = 3,
    [pbr::OriginalName("CLIENT_STATE_TEARDOWN")] Teardown = 4,
  }

  #endregion

}

#endregion Designer generated code
