// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: engine/visitor/api/constants.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace DF.Game.Engine.Service.Visitor.API.Constants {

  /// <summary>Holder for reflection information generated from engine/visitor/api/constants.proto</summary>
  public static partial class ConstantsReflection {

    #region Descriptor
    /// <summary>File descriptor for engine/visitor/api/constants.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static ConstantsReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CiJlbmdpbmUvdmlzaXRvci9hcGkvY29uc3RhbnRzLnByb3RvEilnYW1lLmVu",
            "Z2luZS5zZXJ2aWNlLnZpc2l0b3IuYXBpLmNvbnN0YW50cypQCglBZ2VudFR5",
            "cGUSFgoSQUdFTlRfVFlQRV9VTktOT1dOEAASEgoOQUdFTlRfVFlQRV9GU00Q",
            "ARIXChNBR0VOVF9UWVBFX0ZTTV9MSVNUEAIqiQEKC1Zpc2l0b3JUeXBlEhgK",
            "FFZJU0lUT1JfVFlQRV9VTktOT1dOEAASFQoRVklTSVRPUl9UWVBFX01PVkUQ",
            "ARIYChRWSVNJVE9SX1RZUEVfUFJPRFVDRRACEhYKElZJU0lUT1JfVFlQRV9D",
            "SEFTRRADEhcKE1ZJU0lUT1JfVFlQRV9BVFRBQ0sQBEJZWihnYW1lLnNlcnZl",
            "ci5lbmdpbmUudmlzaXRvci5hcGkuY29uc3RhbnRzqgIsREYuR2FtZS5Fbmdp",
            "bmUuU2VydmljZS5WaXNpdG9yLkFQSS5Db25zdGFudHNiBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::DF.Game.Engine.Service.Visitor.API.Constants.AgentType), typeof(global::DF.Game.Engine.Service.Visitor.API.Constants.VisitorType), }, null, null));
    }
    #endregion

  }
  #region Enums
  public enum AgentType {
    [pbr::OriginalName("AGENT_TYPE_UNKNOWN")] Unknown = 0,
    [pbr::OriginalName("AGENT_TYPE_FSM")] Fsm = 1,
    [pbr::OriginalName("AGENT_TYPE_FSM_LIST")] FsmList = 2,
  }

  public enum VisitorType {
    [pbr::OriginalName("VISITOR_TYPE_UNKNOWN")] Unknown = 0,
    [pbr::OriginalName("VISITOR_TYPE_MOVE")] Move = 1,
    [pbr::OriginalName("VISITOR_TYPE_PRODUCE")] Produce = 2,
    [pbr::OriginalName("VISITOR_TYPE_CHASE")] Chase = 3,
    [pbr::OriginalName("VISITOR_TYPE_ATTACK")] Attack = 4,
  }

  #endregion

}

#endregion Designer generated code
