// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: pathing/api/constants.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace DF.Game.Pathing.API.Constants {

  /// <summary>Holder for reflection information generated from pathing/api/constants.proto</summary>
  public static partial class ConstantsReflection {

    #region Descriptor
    /// <summary>File descriptor for pathing/api/constants.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static ConstantsReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChtwYXRoaW5nL2FwaS9jb25zdGFudHMucHJvdG8SGmdhbWUucGF0aGluZy5h",
            "cGkuY29uc3RhbnRzKnQKCURpcmVjdGlvbhIVChFESVJFQ1RJT05fVU5LTk9X",
            "ThAAEhMKD0RJUkVDVElPTl9OT1JUSBABEhMKD0RJUkVDVElPTl9TT1VUSBAC",
            "EhIKDkRJUkVDVElPTl9FQVNUEAMSEgoORElSRUNUSU9OX1dFU1QQBCpLCghF",
            "ZGdlVHlwZRIVChFFREdFX1RZUEVfVU5LTk9XThAAEhMKD0VER0VfVFlQRV9J",
            "TlRFUhABEhMKD0VER0VfVFlQRV9JTlRSQRACKlwKC09yaWVudGF0aW9uEhcK",
            "E09SSUVOVEFUSU9OX1VOS05PV04QABIaChZPUklFTlRBVElPTl9IT1JJWk9O",
            "VEFMEAESGAoUT1JJRU5UQVRJT05fVkVSVElDQUwQAkI8WhpnYW1lLnBhdGhp",
            "bmcuYXBpLmNvbnN0YW50c6oCHURGLkdhbWUuUGF0aGluZy5BUEkuQ29uc3Rh",
            "bnRzYgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::DF.Game.Pathing.API.Constants.Direction), typeof(global::DF.Game.Pathing.API.Constants.EdgeType), typeof(global::DF.Game.Pathing.API.Constants.Orientation), }, null, null));
    }
    #endregion

  }
  #region Enums
  public enum Direction {
    [pbr::OriginalName("DIRECTION_UNKNOWN")] Unknown = 0,
    [pbr::OriginalName("DIRECTION_NORTH")] North = 1,
    [pbr::OriginalName("DIRECTION_SOUTH")] South = 2,
    [pbr::OriginalName("DIRECTION_EAST")] East = 3,
    [pbr::OriginalName("DIRECTION_WEST")] West = 4,
  }

  public enum EdgeType {
    [pbr::OriginalName("EDGE_TYPE_UNKNOWN")] Unknown = 0,
    [pbr::OriginalName("EDGE_TYPE_INTER")] Inter = 1,
    [pbr::OriginalName("EDGE_TYPE_INTRA")] Intra = 2,
  }

  public enum Orientation {
    [pbr::OriginalName("ORIENTATION_UNKNOWN")] Unknown = 0,
    [pbr::OriginalName("ORIENTATION_HORIZONTAL")] Horizontal = 1,
    [pbr::OriginalName("ORIENTATION_VERTICAL")] Vertical = 2,
  }

  #endregion

}

#endregion Designer generated code
