// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: map/api/constants.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace DF.Game.Map.API.Constants {

  /// <summary>Holder for reflection information generated from map/api/constants.proto</summary>
  public static partial class ConstantsReflection {

    #region Descriptor
    /// <summary>File descriptor for map/api/constants.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static ConstantsReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChdtYXAvYXBpL2NvbnN0YW50cy5wcm90bxIWZ2FtZS5tYXAuYXBpLmNvbnN0",
            "YW50cypaCgtUZXJyYWluVHlwZRIYChRURVJSQUlOX1RZUEVfVU5LTk9XThAA",
            "EhgKFFRFUlJBSU5fVFlQRV9CTE9DS0VEEAESFwoTVEVSUkFJTl9UWVBFX1BM",
            "QUlOUxACQjRaFmdhbWUubWFwLmFwaS5jb25zdGFudHOqAhlERi5HYW1lLk1h",
            "cC5BUEkuQ29uc3RhbnRzYgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::DF.Game.Map.API.Constants.TerrainType), }, null, null));
    }
    #endregion

  }
  #region Enums
  public enum TerrainType {
    [pbr::OriginalName("TERRAIN_TYPE_UNKNOWN")] Unknown = 0,
    [pbr::OriginalName("TERRAIN_TYPE_BLOCKED")] Blocked = 1,
    [pbr::OriginalName("TERRAIN_TYPE_PLAINS")] Plains = 2,
  }

  #endregion

}

#endregion Designer generated code
